
test_url=https://api.themoviedb.org/3/discover/movie?api_key=70cb6bbe42e70d00630d60e98da21a75&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=2&with_genres=878&with_watch_monetization_types=flatrate
external_api_url=https://api.themoviedb.org/3/discover/movie?api_key=70cb6bbe42e70d00630d60e98da21a75&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&with_watch_monetization_types=flatrate
spring.datasource.url=jdbc:mysql://localhost:3306/movieapidb
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
